# SPDX-License-Identifier: GPL-2.0

# Platform Driver
snd-soc-mt8163-afe-y := \
	mt8163-afe-clk.o \
	mt8163-afe-pcm.o \
	mt8163-dai-i2s.o

obj-$(CONFIG_SND_SOC_MT8163) += snd-soc-mt8163-afe.o

# Machine support
obj-$(CONFIG_SND_SOC_MT8163_TLV320AIC32X4) += mt8163-tlv320aic32x4.o
