/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */

#ifndef _DT_BINDINGS_CLOCK_MT8163_APMIXEDSYS_H
#define _DT_BINDINGS_CLOCK_MT8163_APMIXEDSYS_H

#define CLK_APMIXED_ARMPLL	0
#define CLK_APMIXED_MAINPLL	1
#define CLK_APMIXED_UNIVPLL	2
#define CLK_APMIXED_MMPLL	3
#define CLK_APMIXED_MSDCPLL	4
#define CLK_APMIXED_VENCPLL	5
#define CLK_APMIXED_TVDPLL	6
#define CLK_APMIXED_MPLL	7
#define CLK_APMIXED_AUD1PLL	8
#define CLK_APMIXED_AUD2PLL	9
#define CLK_APMIXED_LVDSPLL	10
#define CLK_APMIXED_SSUSB_26M	11
#define CLK_APMIXED_ARMPLL_26M	12
#define CLK_APMIXED_MIPI_26M	13
#define CLK_APMIXED_REF2USB_TX	14
#define CLK_APMIXED_NR_CLK	15

#endif /* _DT_BINDINGS_CLOCK_MT8163_APMIXEDSYS_H */
