/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */

#ifndef _DT_BINDINGS_CLOCK_MT8163_AUDSYS_H
#define _DT_BINDINGS_CLOCK_MT8163_AUDSYS_H

#define CLK_AUDIO_AFE		0
#define CLK_AUDIO_I2S		1
#define CLK_AUDIO_22M		2
#define CLK_AUDIO_24M		3
#define CLK_AUDIO_SPDF2		4
#define CLK_AUDIO_APLL2_TUNER	5
#define CLK_AUDIO_APLL_TUNER	6
#define CLK_AUDIO_HDMI		7
#define CLK_AUDIO_SPDF		8
#define CLK_AUDIO_ADC		9
#define CLK_AUDIO_DAC		10
#define CLK_AUDIO_DAC_PREDIS	11
#define CLK_AUDIO_TML		12
#define CLK_AUDIO_APLL1_DIV0	13
#define CLK_AUDIO_APLL2_DIV0	14
#define CLK_AUDIO_APLL_I2S0	15
#define CLK_AUDIO_APLL_I2S1	16
#define CLK_AUDIO_APLL_I2S2	17
#define CLK_AUDIO_APLL_I2S3	18

#endif /* _DT_BINDINGS_CLOCK_MT8163_AUDSYS_H */
