#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += jd936x_wxga_dsi_vdo_crown.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/leds/mt8163
